// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAe1pw9KLsLjt2bHQ1XkHPcfXoz02fw84A',
    appId: '1:908327758113:web:3cf11bbbe49ec65844b660',
    messagingSenderId: '908327758113',
    projectId: 'my-demo-project-2b99b',
    authDomain: 'my-demo-project-2b99b.firebaseapp.com',
    storageBucket: 'my-demo-project-2b99b.appspot.com',
    measurementId: 'G-2TTCP9DS2L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQXHQN7M5uxtC82qCWnOf7rxAat_30MEk',
    appId: '1:908327758113:android:e6f6abcd8dda520544b660',
    messagingSenderId: '908327758113',
    projectId: 'my-demo-project-2b99b',
    storageBucket: 'my-demo-project-2b99b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgewxXnw6P62tIHzUigTYutUN8xAoJndk',
    appId: '1:908327758113:ios:7e96bd423671cdf644b660',
    messagingSenderId: '908327758113',
    projectId: 'my-demo-project-2b99b',
    storageBucket: 'my-demo-project-2b99b.appspot.com',
    iosClientId: '908327758113-0q70at6rhggltjb3nf0gd23jclke03cm.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirstDemoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgewxXnw6P62tIHzUigTYutUN8xAoJndk',
    appId: '1:908327758113:ios:7e96bd423671cdf644b660',
    messagingSenderId: '908327758113',
    projectId: 'my-demo-project-2b99b',
    storageBucket: 'my-demo-project-2b99b.appspot.com',
    iosClientId: '908327758113-0q70at6rhggltjb3nf0gd23jclke03cm.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirstDemoApp',
  );
}
